name: MobTime Build

on:
  push:
    branches-ignore:
      - master
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21.0.1
          java-package: jdk
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew jpackage -PinstallerType=deb
      - uses: actions/upload-artifact@v3
        with:
          name: MobTime-Linux
          path: ./build/jpackage/mobtime*.deb
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21.0.1
          java-package: jdk
          cache: 'gradle'
      - name: Download Wix
        shell: powershell
        run: Invoke-WebRequest -Uri https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe -OutFile wix311.exe
      - name: Install Wix
        shell: powershell
        run: ./wix311.exe /install /quiet /norestart
      - name: Build with Gradle
        shell: powershell
        run: ./gradlew.bat jpackage -PinstallerType=msi
      - uses: actions/upload-artifact@v3
        with:
          name: MobTime-Windows
          path: build/jpackage/mobtime*.msi
  build_mac_amd64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21.0.1
          java-package: jdk
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew jpackage -PinstallerType=pkg
      - uses: actions/upload-artifact@v3
        with:
          name: MobTime-Mac-x86
          path: build/jpackage/mobtime-*.pkg
  build_mac_arm64:
    runs-on: mbpro-m3
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21.0.1
          java-package: jdk
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew jpackage -PinstallerType=pkg
      - uses: actions/upload-artifact@v3
        with:
          name: MobTime-Mac-arm64
          path: build/jpackage/mobtime*.pkg      
