name: MobTime Build

on:
  push:
    branches-ignore:
      - master
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15.0.1
          java-package: jdk
      - name: Build with Gradle
        run: ./gradlew jpackage -PinstallerType=deb
      - uses: actions/upload-artifact@v2
        with:
          name: MobTime-Linux
          path: ./build/jpackage/mobtime_*-1_amd64.deb
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15.0.1
          java-package: jdk
      - name: Download Wix
        shell: powershell
        run: Invoke-WebRequest -Uri https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe -OutFile wix311.exe
      - name: Install Wix
        shell: powershell
        run: ./wix311.exe /install /quiet /norestart
      - name: Build with Gradle
        shell: powershell
        run: ./gradlew.bat jpackage -PinstallerType=msi
      - uses: actions/upload-artifact@v2
        with:
          name: MobTime-Windows
          path: build/jpackage/MobTime-*.msi
  build_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15.0.1
          java-package: jdk
      - name: Build with Gradle
        run: ./gradlew jpackage -PinstallerType=pkg
      - uses: actions/upload-artifact@v2
        with:
          name: MobTime-Mac
          path: build/jpackage/MobTime-*.pkg
