name: MobTime Release

on:
  push:
    branches:
      - master
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version_semver: ${{ steps.version.outputs.version_semver }}
    steps:
      - uses: actions/checkout@v2
      - name: Version
        id: version
        run: echo "::set-output name=version_semver::1.7.6"
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version_semver }}
          release_name: MobTime  v${{ steps.version.outputs.version_semver }}
          body_path: release.md
  build_linux:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15.0.1
          java-package: jdk
      - name: Build with Gradle
        run: ./gradlew jpackage -PinstallerType=deb
      - uses: actions/upload-artifact@v2
        with:
          name: MobTime-Linux
          path: ./build/jpackage/mobtime_${{ needs.create_release.outputs.version_semver }}-1_amd64.deb
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/jpackage/mobtime_${{ needs.create_release.outputs.version_semver }}-1_amd64.deb
          asset_name: mobtime_${{ needs.create_release.outputs.version_semver }}-1_amd64.deb
          asset_content_type: application/deb
  build_windows:
    needs: create_release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15.0.1
          java-package: jdk
      - name: Download Wix
        shell: powershell
        run: Invoke-WebRequest -Uri https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe -OutFile wix311.exe
      - name: Install Wix
        shell: powershell
        run: ./wix311.exe /install /quiet /norestart
      - name: Build with Gradle
        shell: powershell
        run: ./gradlew.bat jpackage -PinstallerType=msi
      - uses: actions/upload-artifact@v2
        with:
          name: MobTime-Windows
          path: build/jpackage/MobTime-${{ needs.create_release.outputs.version_semver }}.msi
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/jpackage/MobTime-${{ needs.create_release.outputs.version_semver }}.msi
          asset_name: MobTime-${{ needs.create_release.outputs.version_semver }}.msi
          asset_content_type: application/msi
  build_mac:
    needs: create_release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15.0.1
          java-package: jdk
      - name: Build with Gradle
        run: ./gradlew jpackage -PinstallerType=pkg
      - uses: actions/upload-artifact@v2
        with:
          name: MobTime-Mac
          path: build/jpackage/MobTime-${{ needs.create_release.outputs.version_semver }}.pkg
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/jpackage/MobTime-${{ needs.create_release.outputs.version_semver }}.pkg
          asset_name: MobTime-${{ needs.create_release.outputs.version_semver }}.pkg
          asset_content_type: application/pkg