name: MobTime Release

on:
  push:
    branches:
      - master
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version_semver: ${{ steps.version.outputs.version_semver }}
    steps:
      - uses: actions/checkout@v4
      - name: Version
        id: version
        run: echo "version_semver=1.7.8" >> $GITHUB_OUTPUT
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version_semver }}
          name: MobTime  v${{ steps.version.outputs.version_semver }}
          body_path: release.md
  build_linux:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21.0.1
          java-package: jdk
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew jpackage -PinstallerType=deb
      - uses: actions/upload-artifact@v3
        with:
          name: MobTime-Linux
          path: ./build/jpackage/mobtime*.deb
      - name: Upload
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.create_release.outputs.version_semver }}
          name: MobTime  v${{ needs.create_release.outputs.version_semver }}
          files: |
            build/jpackage/mobtime-linux_${{ needs.create_release.outputs.version_semver }}_amd64.deb
  build_windows:
    needs: create_release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21.0.1
          java-package: jdk
          cache: 'gradle'
      - name: Download Wix
        shell: powershell
        run: Invoke-WebRequest -Uri https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe -OutFile wix311.exe
      - name: Install Wix
        shell: powershell
        run: ./wix311.exe /install /quiet /norestart
      - name: Build with Gradle
        shell: powershell
        run: ./gradlew.bat jpackage -PinstallerType=msi
      - uses: actions/upload-artifact@v3
        with:
          name: MobTime-Windows
          path: build/jpackage/mobtime*.msi
      - name: Upload
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.create_release.outputs.version_semver }}
          name: MobTime  v${{ needs.create_release.outputs.version_semver }}
          files: |
            build/jpackage/mobtime-windows-x86-64-${{ needs.create_release.outputs.version_semver }}.msi
  build_mac_amd64:
    needs: create_release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21.0.1
          java-package: jdk
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew jpackage -PinstallerType=pkg
      - uses: actions/upload-artifact@v3
        with:
          name: MobTime-Mac-amd64
          path: build/jpackage/mobtime*.pkg
      - name: Upload
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.create_release.outputs.version_semver }}
          name: MobTime  v${{ needs.create_release.outputs.version_semver }}
          files: |
            build/jpackage/mobtime-macos-x86-64-${{ needs.create_release.outputs.version_semver }}.pkg
  build_mac_arm64:
    needs: create_release
    runs-on: mbpro-m3
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21.0.1
          java-package: jdk
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew jpackage -PinstallerType=pkg
      - uses: actions/upload-artifact@v3
        with:
          name: MobTime-Mac-amd64
          path: build/jpackage/mobtime*.pkg
      - name: Upload
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.create_release.outputs.version_semver }}
          name: MobTime  v${{ needs.create_release.outputs.version_semver }}
          files: |
            build/jpackage/mobtime-macos-aarch64-${{ needs.create_release.outputs.version_semver }}.pkg
